In [2]:
import torch

torch.__version__

'2.5.1'

## 创建Tensor

In [2]:
# 随机int
torch.manual_seed(42)
a = torch.randint(1, 10, (2, 3), dtype=torch.int8)
a

tensor([[7, 6, 8],
        [5, 1, 3]], dtype=torch.int8)

In [133]:
# 随机0-1均匀分布
torch.manual_seed(42)
b = torch.rand((2, 3), dtype=torch.float16)
b

tensor([[0.5498, 0.7124, 0.4199],
        [0.6318, 0.5518, 0.5347]], dtype=torch.float16)

In [134]:
b.numpy()

array([[0.55  , 0.7124, 0.42  ],
       [0.632 , 0.552 , 0.5347]], dtype=float16)

In [135]:
c = torch.tensor(1, dtype=torch.int16)
c

tensor(1, dtype=torch.int16)

In [136]:
c.numpy()

array(1, dtype=int16)

In [137]:
d = torch.tensor(1.0, dtype=torch.float32)
d

tensor(1.)

In [138]:
d.item()

1.0

## 基本操作

### 数学运算

#### 代数运算

In [139]:
a + a

tensor([[14, 12, 16],
        [10,  2,  6]], dtype=torch.int8)

In [140]:
# 广播
c * b

tensor([[0.5498, 0.7124, 0.4199],
        [0.6318, 0.5518, 0.5347]], dtype=torch.float16)

In [141]:
# 广播
b * 1

tensor([[0.5498, 0.7124, 0.4199],
        [0.6318, 0.5518, 0.5347]], dtype=torch.float16)

In [142]:
torch.manual_seed(42)
a = torch.randint(1, 10, (2, 3), dtype=torch.int8)
a

tensor([[7, 6, 8],
        [5, 1, 3]], dtype=torch.int8)

In [143]:
a ** 2

tensor([[49, 36, 64],
        [25,  1,  9]], dtype=torch.int8)

In [144]:
a ** b

tensor([[2.9141, 3.5840, 2.3945],
        [2.7637, 1.0000, 1.7988]], dtype=torch.float16)

In [145]:
7 ** 0.5498

2.914975456235201

In [57]:
a.exp()

tensor([[1.0966e+03, 4.0343e+02, 2.9810e+03],
        [1.4841e+02, 2.7183e+00, 2.0086e+01]])

In [64]:
a.log()

tensor([[1.9459, 1.7918, 2.0794],
        [1.6094, 0.0000, 1.0986]])

In [65]:
a.exp().log()

tensor([[7.0000, 6.0000, 8.0000],
        [5.0000, 1.0000, 3.0000]])

#### 向量运算

In [17]:
a = torch.tensor([1,2,3], dtype=torch.int16)
b = torch.arange(4, 7, dtype=torch.int16)
a, b

(tensor([1, 2, 3], dtype=torch.int16), tensor([4, 5, 6], dtype=torch.int16))

In [18]:
a * b

tensor([ 4, 10, 18], dtype=torch.int16)

In [19]:
# 点积、内积
a.dot(b)

tensor(32, dtype=torch.int16)

In [20]:
# 外积
a.outer(b)

tensor([[ 4,  5,  6],
        [ 8, 10, 12],
        [12, 15, 18]], dtype=torch.int16)

#### 矩阵运算

In [21]:
# 随机int
torch.manual_seed(42)
a = torch.randint(1, 10, (2, 3), dtype=torch.int32)
b = torch.randint(1, 10, (3, 2), dtype=torch.int32)
a, b

(tensor([[7, 6, 8],
         [5, 1, 3]], dtype=torch.int32),
 tensor([[8, 6],
         [5, 3],
         [5, 5]], dtype=torch.int32))

In [22]:
# 矩阵乘法
a @ b

tensor([[126, 100],
        [ 60,  48]], dtype=torch.int32)

In [23]:
# 转置
a.T

tensor([[7, 5],
        [6, 1],
        [8, 3]], dtype=torch.int32)

In [27]:
a.t()

tensor([[7, 5],
        [6, 1],
        [8, 3]], dtype=torch.int32)

In [38]:
# 随机int
torch.manual_seed(42)
c = torch.rand( (3, 3))
c

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

In [39]:
torch.inverse(c)

tensor([[ 0.2074,  1.0543, -0.7579],
        [ 1.4166, -1.3853,  0.3083],
        [-1.2516,  0.8811,  1.0095]])

In [40]:
torch.inverse(c) @ c

tensor([[ 1.0000e+00, -1.4607e-08, -6.7945e-08],
        [-1.2975e-08,  1.0000e+00,  3.1702e-09],
        [ 2.2241e-08, -1.0358e-07,  1.0000e+00]])

In [43]:
eigvals, eigvecs = torch.linalg.eig(c)

In [44]:
eigvals

tensor([ 2.0435+0.j,  0.6005+0.j, -0.4305+0.j])

In [45]:
eigvecs

tensor([[-0.6218+0.j, -0.5497+0.j,  0.4506+0.j],
        [-0.5599+0.j, -0.1727+0.j, -0.8066+0.j],
        [-0.5476+0.j,  0.8173+0.j,  0.3825+0.j]])

In [58]:
# A=VDV^-1
eigvecs @ torch.diag_embed(eigvals) @ torch.inverse(eigvecs)

tensor([[0.8823+0.j, 0.9150+0.j, 0.3829+0.j],
        [0.9593+0.j, 0.3904+0.j, 0.6009+0.j],
        [0.2566+0.j, 0.7936+0.j, 0.9408+0.j]])

#### 张量运算

In [3]:
# 随机int
torch.manual_seed(42)
a = torch.randint(1, 10, (2, 3, 4, 5), dtype=torch.int32)
b = torch.randint(1, 10, (2, 3, 5, 6), dtype=torch.int32)

In [4]:
a

tensor([[[[7, 6, 8, 5, 1],
          [3, 8, 6, 5, 3],
          [5, 5, 9, 1, 1],
          [5, 3, 5, 4, 5]],

         [[5, 9, 2, 6, 9],
          [5, 3, 1, 2, 2],
          [4, 4, 8, 8, 9],
          [8, 3, 6, 2, 4]],

         [[3, 4, 2, 4, 4],
          [9, 6, 5, 1, 3],
          [4, 1, 2, 1, 8],
          [5, 2, 6, 6, 4]]],


        [[[3, 4, 3, 8, 1],
          [6, 7, 2, 8, 8],
          [9, 1, 8, 8, 8],
          [3, 4, 2, 9, 6]],

         [[7, 5, 3, 4, 5],
          [3, 8, 1, 3, 2],
          [5, 3, 4, 7, 8],
          [3, 8, 8, 6, 9]],

         [[8, 4, 1, 6, 5],
          [7, 1, 2, 8, 4],
          [7, 1, 7, 1, 6],
          [3, 3, 8, 1, 1]]]], dtype=torch.int32)

In [114]:
(a @ b).shape

torch.Size([2, 3, 4, 6])

In [115]:
torch.matmul(a,b).shape

torch.Size([2, 3, 4, 6])

In [118]:
a.matmul(b).shape

torch.Size([2, 3, 4, 6])

In [116]:
torch.matmul(a,b)==(a@b)

tensor([[[[True, True, True, True, True, True],
          [True, True, True, True, True, True],
          [True, True, True, True, True, True],
          [True, True, True, True, True, True]],

         [[True, True, True, True, True, True],
          [True, True, True, True, True, True],
          [True, True, True, True, True, True],
          [True, True, True, True, True, True]],

         [[True, True, True, True, True, True],
          [True, True, True, True, True, True],
          [True, True, True, True, True, True],
          [True, True, True, True, True, True]]],


        [[[True, True, True, True, True, True],
          [True, True, True, True, True, True],
          [True, True, True, True, True, True],
          [True, True, True, True, True, True]],

         [[True, True, True, True, True, True],
          [True, True, True, True, True, True],
          [True, True, True, True, True, True],
          [True, True, True, True, True, True]],

         [[True, True, True,

In [65]:
# 广播扩展，注意第二个维度一个是1，第一个维度必须相等
torch.matmul(torch.randint(1, 10, (2, 1, 8, 5)), torch.randint(1, 10, (2, 3, 5, 7))).shape

torch.Size([2, 3, 8, 7])

#### 关系运算

In [69]:
c = torch.tensor(1, dtype=torch.int16)
c

tensor(1, dtype=torch.int16)

In [70]:
d = torch.tensor(1.0, dtype=torch.float32)
d

tensor(1.)

In [121]:
c == d

tensor(True)

In [127]:
torch.all(torch.matmul(a,b) == (a@b))

tensor(True)

In [67]:
# 随机int
torch.manual_seed(42)
a = torch.randint(1, 10, (2, 3), dtype=torch.int32)
b = torch.randint(1, 10, (2, 3), dtype=torch.int32)
a, b

(tensor([[7, 6, 8],
         [5, 1, 3]], dtype=torch.int32),
 tensor([[8, 6, 5],
         [3, 5, 5]], dtype=torch.int32))

In [4]:
a > b

tensor([[False, False,  True],
        [ True, False, False]])

In [68]:
torch.allclose(a,b)

False

In [5]:
e = torch.rand((2,3,4))
e

tensor([[[0.5161, 0.3939, 0.3278, 0.2606],
         [0.0931, 0.9193, 0.2999, 0.6325],
         [0.3265, 0.5406, 0.9662, 0.7304]],

        [[0.0667, 0.6985, 0.9746, 0.6315],
         [0.8352, 0.9929, 0.4234, 0.6038],
         [0.1525, 0.3970, 0.8703, 0.7563]]])

In [84]:
torch.allclose(e, e+1e-8)

True

### 元素选取

In [3]:
torch.manual_seed(42)
a = torch.randint(1, 10, (4, 4), dtype=torch.int8)
a

tensor([[7, 6, 8, 5],
        [1, 3, 8, 6],
        [5, 3, 5, 5],
        [9, 1, 1, 5]], dtype=torch.int8)

#### 索引

In [8]:
ix = a[[1,2],[2]]
ix

tensor([8, 5], dtype=torch.int8)

In [9]:
ix[0] = -3
ix

tensor([-3,  5], dtype=torch.int8)

In [10]:
a

tensor([[7, 6, 8, 5],
        [1, 3, 8, 6],
        [5, 3, 5, 5],
        [9, 1, 1, 5]], dtype=torch.int8)

#### 切片

In [11]:
slice = a[:2, :3]
slice

tensor([[7, 6, 8],
        [1, 3, 8]], dtype=torch.int8)

In [170]:
slice[0][0] = -7

In [171]:
a

tensor([[-7,  6,  8,  5],
        [ 1,  3,  8,  6],
        [ 5,  3,  5,  5],
        [ 9,  1,  1,  5]], dtype=torch.int8)

In [167]:
# clone后会有新的副本

In [172]:
slice = a[:2,:3].clone()
slice

tensor([[-7,  6,  8],
        [ 1,  3,  8]], dtype=torch.int8)

In [173]:
slice[0][0] = -77

In [174]:
a

tensor([[-7,  6,  8,  5],
        [ 1,  3,  8,  6],
        [ 5,  3,  5,  5],
        [ 9,  1,  1,  5]], dtype=torch.int8)

#### 切片索引

In [112]:
ixslice = a[:2,3]
ixslice

tensor([5, 6], dtype=torch.int8)

In [113]:
ixslice[0] = -5

In [114]:
a

tensor([[-7,  6,  8, -5],
        [ 1,  3,  8,  6],
        [ 5,  3,  5,  5],
        [ 9,  1,  1,  5]], dtype=torch.int8)

#### 极值

In [14]:
torch.manual_seed(42)
a = torch.randint(1, 10, (4, 4), dtype=torch.int8)
a

tensor([[7, 6, 8, 5],
        [1, 3, 8, 6],
        [5, 3, 5, 5],
        [9, 1, 1, 5]], dtype=torch.int8)

In [121]:
a.max(0)

torch.return_types.max(
values=tensor([9, 6, 8, 6], dtype=torch.int8),
indices=tensor([3, 0, 0, 1]))

In [122]:
torch.max(a, 1)

torch.return_types.max(
values=tensor([8, 8, 5, 9], dtype=torch.int8),
indices=tensor([2, 2, 0, 0]))

In [125]:
torch.argmax(a,1)

tensor([2, 2, 0, 0])

#### 随机

In [145]:
# 随机index
torch.randint(0, 10, (2,3))

tensor([[9, 2, 0],
        [5, 9, 3]])

In [139]:
# 随机排列
torch.randperm(5)

tensor([3, 2, 1, 4, 0])

### 元素修改

#### 调整shape

In [6]:
torch.manual_seed(42)
a = torch.randint(1, 10, (3, 4), dtype=torch.int32)
a

tensor([[7, 6, 8, 5],
        [1, 3, 8, 6],
        [5, 3, 5, 5]], dtype=torch.int32)

In [7]:
a.reshape((4,3))

tensor([[7, 6, 8],
        [5, 1, 3],
        [8, 6, 5],
        [3, 5, 5]], dtype=torch.int32)

In [8]:
a.reshape((4,4))

RuntimeError: shape '[4, 4]' is invalid for input of size 12

In [187]:
# view 适合continuous的，reshape适合任意的张量
a.view((2, 6))

tensor([[7, 6, 8, 5, 1, 3],
        [8, 6, 5, 3, 5, 5]], dtype=torch.int32)

In [188]:
a.is_contiguous()

True

#### 调整类型

In [189]:
torch.manual_seed(42)
a = torch.randint(1, 10, (2,3), dtype=torch.int32)
a

tensor([[7, 6, 8],
        [5, 1, 3]], dtype=torch.int32)

In [192]:
a.float().dtype

torch.float32

In [194]:
a.float().int()

tensor([[7, 6, 8],
        [5, 1, 3]], dtype=torch.int32)

In [195]:
a.half()

tensor([[7., 6., 8.],
        [5., 1., 3.]], dtype=torch.float16)

In [198]:
a.type(torch.int8)

tensor([[7, 6, 8],
        [5, 1, 3]], dtype=torch.int8)

In [199]:
a.type(torch.bool)

tensor([[True, True, True],
        [True, True, True]])

#### 调整维度

In [13]:
torch.manual_seed(42)
a = torch.randint(1, 10, (2, 3), dtype=torch.int32)
a

tensor([[7, 6, 8],
        [5, 1, 3]], dtype=torch.int32)

In [14]:
a.unsqueeze(0)

tensor([[[7, 6, 8],
         [5, 1, 3]]], dtype=torch.int32)

In [11]:
a.unsqueeze(0).shape

torch.Size([1, 2, 3])

In [12]:
a

tensor([[7, 6, 8],
        [5, 1, 3]], dtype=torch.int32)

In [183]:
a.unsqueeze(0).squeeze(0)

tensor([[7, 6, 8],
        [5, 1, 3]], dtype=torch.int32)

In [15]:
a[None,:]

tensor([[[7, 6, 8],
         [5, 1, 3]]], dtype=torch.int32)

In [201]:
a[None,:].shape

torch.Size([1, 2, 3])

In [209]:
a[:,[-1]].shape, a[:,None,-1].shape

(torch.Size([2, 1]), torch.Size([2, 1]))

In [210]:
a[:,[-1]]

tensor([[8],
        [3]], dtype=torch.int32)

In [211]:
a[:,None,-1]

tensor([[8],
        [3]], dtype=torch.int32)

In [212]:
a[:,-1,None]

tensor([[8],
        [3]], dtype=torch.int32)

In [217]:
a[None,:,-1]

tensor([[8, 3]], dtype=torch.int32)

想想上面这几个例子，为什么？

#### 拆分

In [23]:
torch.manual_seed(42)
a = torch.randint(1, 10, (5, 4), dtype=torch.int32)
a

tensor([[7, 6, 8, 5],
        [1, 3, 8, 6],
        [5, 3, 5, 5],
        [9, 1, 1, 5],
        [3, 5, 4, 5]], dtype=torch.int32)

In [24]:
torch.split(a, (3, 2))

(tensor([[7, 6, 8, 5],
         [1, 3, 8, 6],
         [5, 3, 5, 5]], dtype=torch.int32),
 tensor([[9, 1, 1, 5],
         [3, 5, 4, 5]], dtype=torch.int32))

In [25]:
torch.tensor_split(a, (3,2))

(tensor([[7, 6, 8, 5],
         [1, 3, 8, 6],
         [5, 3, 5, 5]], dtype=torch.int32),
 tensor([], size=(0, 4), dtype=torch.int32),
 tensor([[5, 3, 5, 5],
         [9, 1, 1, 5],
         [3, 5, 4, 5]], dtype=torch.int32))

In [19]:
torch.split(a, (2, 3))

(tensor([[7, 6, 8, 5],
         [1, 3, 8, 6]], dtype=torch.int32),
 tensor([[5, 3, 5, 5],
         [9, 1, 1, 5],
         [3, 5, 4, 5]], dtype=torch.int32))

In [20]:
torch.tensor_split(a, (2,))

(tensor([[7, 6, 8, 5],
         [1, 3, 8, 6]], dtype=torch.int32),
 tensor([[5, 3, 5, 5],
         [9, 1, 1, 5],
         [3, 5, 4, 5]], dtype=torch.int32))

In [21]:
a.split(2, 0)

(tensor([[7, 6, 8, 5],
         [1, 3, 8, 6]], dtype=torch.int32),
 tensor([[5, 3, 5, 5],
         [9, 1, 1, 5]], dtype=torch.int32),
 tensor([[3, 5, 4, 5]], dtype=torch.int32))

In [22]:
a.tensor_split(2)

(tensor([[7, 6, 8, 5],
         [1, 3, 8, 6],
         [5, 3, 5, 5]], dtype=torch.int32),
 tensor([[9, 1, 1, 5],
         [3, 5, 4, 5]], dtype=torch.int32))

#### 合并

In [251]:
torch.manual_seed(42)
a = torch.randint(1, 10, (2, 3), dtype=torch.int32)
b = torch.randint(1, 10, (2, 3), dtype=torch.int32)
a, b

(tensor([[7, 6, 8],
         [5, 1, 3]], dtype=torch.int32),
 tensor([[8, 6, 5],
         [3, 5, 5]], dtype=torch.int32))

In [253]:
torch.stack([a,b]).shape

torch.Size([2, 2, 3])

In [261]:
# concat, concatenate
torch.cat([a,b]).shape

torch.Size([4, 3])

参考资料：

[Introduction to PyTorch Tensors — PyTorch Tutorials 2.1.1+cu121 documentation](https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html)